export const MESSAGE_SENT = "MESSAGE_SENT";
export const MESSAGE_RECEIVE = "MESSAGE_RECEIVE";
export const ADD_USER = "ADD_USER";
export const LOAD_USERS_LIST = "LOAD_USERS_LIST";
export const ACTIVATE_USER = "ACTIVATE_USER";